import mongoose from "mongoose"

// Create consistent ObjectIds for our mock data
const createObjectId = (num: number) => {
  // Create a timestamp-based ObjectId with a consistent suffix
  const timestamp = Math.floor(Date.now() / 1000)
  const suffix = num.toString().padStart(6, '0')
  const hexString = timestamp.toString(16) + "0000000000" + suffix
  return hexString
}

// Mock vendors with GCash numbers for testing
export const mockVendors = [
  { id: "vendor-1", name: "PawMart Supplies", gcashNumber: "09123456789" },
  { id: "vendor-2", name: "Pet Paradise Store", gcashNumber: "09234567890" },
  { id: "vendor-3", name: "Furry Friends Shop", gcashNumber: "09345678901" },
  { id: "vendor-4", name: "Animal Care Plus", gcashNumber: "09456789012" },
]

export const mockProducts = [
  {
    id: createObjectId(1),
    name: "Premium Dog Food - Chicken & Rice",
    description: "High-quality nutrition for adult dogs with real chicken as the first ingredient",
    price: 49.99,
    category: "food",
    petType: "dog",
    image: "/premium-pet-food-bowls.jpg",
    stock: 25,
    featured: true,
    vendor: mockVendors[0],
  },
  {
    id: createObjectId(2),
    name: "Interactive Puzzle Toy",
    description: "Mental stimulation toy that challenges your pet and reduces boredom",
    price: 24.99,
    category: "toys",
    petType: "all",
    image: "/colorful-pet-toys.jpg",
    stock: 15,
    featured: true,
    vendor: mockVendors[1],
  },
  {
    id: createObjectId(3),
    name: "Leather Collar with ID Tag",
    description: "Durable leather collar with personalized ID tag for safety",
    price: 19.99,
    category: "accessories",
    petType: "dog",
    image: "/pet-collars-and-accessories.jpg",
    stock: 30,
    featured: false,
    vendor: mockVendors[2],
  },
  {
    id: createObjectId(4),
    name: "Cat Health Supplement",
    description: "Daily vitamins and minerals to support your cat's overall health",
    price: 34.99,
    category: "health",
    petType: "cat",
    image: "/pet-health-care-products.jpg",
    stock: 20,
    featured: true,
    vendor: mockVendors[3],
  },
  {
    id: createObjectId(5),
    name: "Professional Grooming Kit",
    description: "Complete grooming set with brushes, nail clippers, and shampoo",
    price: 89.99,
    category: "grooming",
    petType: "all",
    image: "/pet-grooming-kit.png",
    stock: 12,
    featured: false,
    vendor: mockVendors[0],
  },
  {
    id: createObjectId(6),
    name: "Cozy Pet Bed - Large",
    description: "Ultra-soft and comfortable bed for large dogs and cats",
    price: 79.99,
    category: "accessories",
    petType: "all",
    image: "/cozy-pet-bed.jpg",
    stock: 18,
    featured: true,
    vendor: mockVendors[1],
  },
  {
    id: createObjectId(7),
    name: "Bird Seed Mix - Premium",
    description: "Nutritious seed blend for all types of pet birds",
    price: 16.99,
    category: "food",
    petType: "bird",
    image: "/bird-seed-mix.jpg",
    stock: 40,
    featured: false,
    vendor: mockVendors[2],
  },
  {
    id: createObjectId(8),
    name: "Aquarium Filter System",
    description: "Advanced filtration system for clean and healthy aquarium water",
    price: 129.99,
    category: "accessories",
    petType: "fish",
    image: "/aquarium-filter.png",
    stock: 8,
    featured: false,
    vendor: mockVendors[3],
  },
  {
    id: createObjectId(9),
    name: "Small Pet Habitat",
    description: "Spacious and secure habitat for rabbits, guinea pigs, and hamsters",
    price: 199.99,
    category: "accessories",
    petType: "small-pets",
    image: "/small-pet-habitat.jpg",
    stock: 5,
    featured: true,
    vendor: mockVendors[0],
  },
  {
    id: createObjectId(10),
    name: "Dental Chew Treats",
    description: "Healthy treats that help clean teeth and freshen breath",
    price: 12.99,
    category: "health",
    petType: "dog",
    image: "/dental-chew-treats.jpg",
    stock: 35,
    featured: false,
    vendor: mockVendors[1],
  },
]

export const mockServices = [
  // Professional Grooming Services
  {
    id: "grooming-basic",
    name: "Basic Grooming Package",
    description: "Essential grooming services including bath, brush, and nail trim",
    price: 45,
    duration: "1-2 hours",
    image: "/pet-grooming-service.png",
    features: ["Warm bath with premium shampoo", "Thorough brushing", "Nail trimming", "Ear cleaning"],
  },
  {
    id: "grooming-premium",
    name: "Premium Grooming Package",
    description: "Complete grooming experience with styling and special treatments",
    price: 85,
    duration: "2-3 hours",
    image: "/premium-pet-grooming.jpg",
    features: [
      "Everything in Basic Package",
      "Professional styling/haircut",
      "Teeth brushing",
      "Aromatherapy treatment",
      "Nail polish (optional)",
    ],
  },
  {
    id: "grooming-deluxe",
    name: "Deluxe Spa Treatment",
    description: "Luxury spa experience with deep conditioning and massage",
    price: 120,
    duration: "3-4 hours",
    image: "/pet-spa-treatment.jpg",
    features: ["Deep conditioning treatment", "Relaxing massage", "Pedicure with nail art", "Cologne application", "Photo session"],
  },
  {
    id: "grooming-cat",
    name: "Feline Grooming Special",
    description: "Specialized grooming services designed specifically for cats",
    price: 55,
    duration: "1.5-2 hours",
    image: "/cat-grooming.jpg",
    features: ["Gentle cat-specific shampoo", "De-shedding treatment", "Nail trimming", "Sanitary trim"],
  },
  {
    id: "grooming-puppy",
    name: "Puppy Introduction Package",
    description: "Gentle first grooming experience for puppies under 6 months",
    price: 35,
    duration: "45 minutes",
    image: "/puppy-grooming.jpg",
    features: ["Gentle introduction to grooming", "Mini bath", "Nail tip trim", "Positive reinforcement"],
  },
  {
    id: "grooming-senior",
    name: "Senior Pet Care Package",
    description: "Gentle grooming services tailored for older pets with special needs",
    price: 65,
    duration: "2 hours",
    image: "/senior-pet-grooming.jpg",
    features: ["Extra gentle handling", "Therapeutic shampoo", "Joint-friendly positioning", "Health monitoring"],
  },
  {
    id: "grooming-mobile",
    name: "Mobile Grooming Service",
    description: "Professional grooming at your doorstep with our mobile unit",
    price: 95,
    duration: "2-3 hours",
    image: "/mobile-grooming.jpg",
    features: ["At-home convenience", "Fully equipped mobile unit", "Stress-free environment", "Flexible scheduling"],
  },
  {
    id: "grooming-show",
    name: "Show Dog Preparation",
    description: "Professional grooming for dog shows and competitions",
    price: 150,
    duration: "4-5 hours",
    image: "/show-dog-grooming.jpg",
    features: ["Breed-specific styling", "Show-quality finish", "Competition preparation", "Expert consultation"],
  },
  // Pet Boarding & Care Services
  {
    id: "boarding-daily",
    name: "Daily Pet Boarding",
    description: "Safe and comfortable day care for your pets while you're away",
    price: 35,
    duration: "8-10 hours",
    image: "/pet-boarding-facility.png",
    features: ["Supervised playtime", "Feeding service", "Comfortable rest areas", "Regular health checks"],
  },
  {
    id: "boarding-overnight",
    name: "Overnight Pet Boarding",
    description: "Extended care with overnight accommodation in our facility",
    price: 65,
    duration: "24 hours",
    image: "/pet-overnight-boarding.jpg",
    features: [
      "Private sleeping quarters",
      "Multiple meals and snacks",
      "Exercise and playtime",
      "24/7 supervision",
      "Emergency vet access",
    ],
  },
  {
    id: "boarding-luxury",
    name: "Luxury Pet Suite",
    description: "Premium accommodation with extra amenities and personalized care",
    price: 95,
    duration: "24 hours",
    image: "/luxury-pet-suite.jpg",
    features: ["Spacious private suite", "Premium bedding", "Gourmet meals", "Daily grooming", "Webcam access"],
  },
  {
    id: "boarding-medical",
    name: "Medical Boarding Care",
    description: "Specialized boarding for pets requiring medication or medical attention",
    price: 85,
    duration: "24 hours",
    image: "/medical-pet-boarding.jpg",
    features: ["Medication administration", "Health monitoring", "Vet-supervised care", "Special diet management"],
  },
  {
    id: "boarding-puppy",
    name: "Puppy Daycare Program",
    description: "Socialization and care program designed specifically for puppies",
    price: 45,
    duration: "6-8 hours",
    image: "/puppy-daycare.jpg",
    features: ["Puppy socialization", "Potty training support", "Age-appropriate play", "Nap time supervision"],
  },
  {
    id: "boarding-senior",
    name: "Senior Pet Care Program",
    description: "Gentle care and monitoring for elderly pets with special needs",
    price: 75,
    duration: "24 hours",
    image: "/senior-pet-care.jpg",
    features: ["Comfortable accommodations", "Gentle exercise", "Medication management", "Extra attention"],
  },
  {
    id: "boarding-cat",
    name: "Feline Boarding Sanctuary",
    description: "Cat-only boarding facility with climbing trees and quiet spaces",
    price: 55,
    duration: "24 hours",
    image: "/cat-boarding.jpg",
    features: ["Cat-only environment", "Climbing structures", "Quiet spaces", "Interactive toys"],
  },
  {
    id: "boarding-exotic",
    name: "Exotic Pet Boarding",
    description: "Specialized care for birds, reptiles, and other exotic pets",
    price: 70,
    duration: "24 hours",
    image: "/exotic-pet-boarding.jpg",
    features: ["Species-specific care", "Climate control", "Specialized diet", "Expert handling"],
  },
  // Training Programs
  {
    id: "training-basic",
    name: "Basic Obedience Training",
    description: "Foundation training for puppies and young dogs",
    price: 120,
    duration: "4 weeks (1 hour/week)",
    image: "/dog-training-class.jpg",
    features: ["Sit, stay, come commands", "Leash training", "House training tips", "Socialization guidance"],
  },
  {
    id: "training-advanced",
    name: "Advanced Training Program",
    description: "Comprehensive training for behavioral issues and advanced commands",
    price: 250,
    duration: "8 weeks (1 hour/week)",
    image: "/advanced-dog-training.png",
    features: [
      "All basic commands",
      "Behavioral modification",
      "Advanced tricks",
      "Aggression management",
      "One-on-one sessions",
    ],
  },
  {
    id: "training-puppy",
    name: "Puppy Kindergarten",
    description: "Early socialization and basic training for puppies 8-16 weeks old",
    price: 100,
    duration: "6 weeks (45 min/week)",
    image: "/puppy-kindergarten.jpg",
    features: ["Early socialization", "Basic commands", "Bite inhibition", "Handling exercises"],
  },
  {
    id: "training-behavioral",
    name: "Behavioral Modification",
    description: "Specialized training for dogs with anxiety, aggression, or other behavioral issues",
    price: 300,
    duration: "10 weeks (1 hour/week)",
    image: "/behavioral-training.jpg",
    features: ["Behavior assessment", "Customized training plan", "Desensitization techniques", "Owner education"],
  },
  {
    id: "training-agility",
    name: "Agility Training Course",
    description: "Fun and challenging agility training for active dogs",
    price: 180,
    duration: "6 weeks (1 hour/week)",
    image: "/agility-training.jpg",
    features: ["Obstacle course training", "Physical fitness", "Mental stimulation", "Competition preparation"],
  },
  {
    id: "training-therapy",
    name: "Therapy Dog Certification",
    description: "Training and certification program for therapy dog candidates",
    price: 350,
    duration: "12 weeks (1 hour/week)",
    image: "/therapy-dog-training.jpg",
    features: ["Temperament evaluation", "Public access training", "Certification preparation", "Ongoing support"],
  },
  {
    id: "training-private",
    name: "Private Training Sessions",
    description: "One-on-one personalized training sessions in your home",
    price: 80,
    duration: "1 hour",
    image: "/private-training.jpg",
    features: ["Customized training plan", "In-home convenience", "Flexible scheduling", "Family involvement"],
  },
  {
    id: "training-cat",
    name: "Feline Behavior Training",
    description: "Behavior modification and training specifically designed for cats",
    price: 150,
    duration: "4 weeks (45 min/week)",
    image: "/cat-training.jpg",
    features: ["Litter box training", "Scratching solutions", "Aggression management", "Environmental enrichment"],
  },
]
