import mongoose from "mongoose"

// Create consistent ObjectIds for our mock data
const createObjectId = (num: number) => {
  // Create a timestamp-based ObjectId with a consistent suffix
  const timestamp = Math.floor(Date.now() / 1000)
  const suffix = num.toString().padStart(6, '0')
  const hexString = timestamp.toString(16) + "0000000000" + suffix
  return hexString
}

export const mockProducts = [
  {
    id: createObjectId(1),
    name: "Premium Dog Food - Chicken & Rice",
    description: "High-quality nutrition for adult dogs with real chicken as the first ingredient",
    price: 49.99,
    category: "food",
    petType: "dog",
    image: "/premium-pet-food-bowls.jpg",
    stock: 25,
    featured: true,
  },
  {
    id: createObjectId(2),
    name: "Interactive Puzzle Toy",
    description: "Mental stimulation toy that challenges your pet and reduces boredom",
    price: 24.99,
    category: "toys",
    petType: "all",
    image: "/colorful-pet-toys.jpg",
    stock: 15,
    featured: true,
  },
  {
    id: createObjectId(3),
    name: "Leather Collar with ID Tag",
    description: "Durable leather collar with personalized ID tag for safety",
    price: 19.99,
    category: "accessories",
    petType: "dog",
    image: "/pet-collars-and-accessories.jpg",
    stock: 30,
    featured: false,
  },
  {
    id: createObjectId(4),
    name: "Cat Health Supplement",
    description: "Daily vitamins and minerals to support your cat's overall health",
    price: 34.99,
    category: "health",
    petType: "cat",
    image: "/pet-health-care-products.jpg",
    stock: 20,
    featured: true,
  },
  {
    id: createObjectId(5),
    name: "Professional Grooming Kit",
    description: "Complete grooming set with brushes, nail clippers, and shampoo",
    price: 89.99,
    category: "grooming",
    petType: "all",
    image: "/pet-grooming-kit.png",
    stock: 12,
    featured: false,
  },
  {
    id: createObjectId(6),
    name: "Cozy Pet Bed - Large",
    description: "Ultra-soft and comfortable bed for large dogs and cats",
    price: 79.99,
    category: "accessories",
    petType: "all",
    image: "/cozy-pet-bed.jpg",
    stock: 18,
    featured: true,
  },
  {
    id: createObjectId(7),
    name: "Bird Seed Mix - Premium",
    description: "Nutritious seed blend for all types of pet birds",
    price: 16.99,
    category: "food",
    petType: "bird",
    image: "/bird-seed-mix.jpg",
    stock: 40,
    featured: false,
  },
  {
    id: createObjectId(8),
    name: "Aquarium Filter System",
    description: "Advanced filtration system for clean and healthy aquarium water",
    price: 129.99,
    category: "accessories",
    petType: "fish",
    image: "/aquarium-filter.png",
    stock: 8,
    featured: false,
  },
  {
    id: createObjectId(9),
    name: "Small Pet Habitat",
    description: "Spacious and secure habitat for rabbits, guinea pigs, and hamsters",
    price: 199.99,
    category: "accessories",
    petType: "small-pets",
    image: "/small-pet-habitat.jpg",
    stock: 5,
    featured: true,
  },
  {
    id: createObjectId(10),
    name: "Dental Chew Treats",
    description: "Healthy treats that help clean teeth and freshen breath",
    price: 12.99,
    category: "health",
    petType: "dog",
    image: "/dental-chew-treats.jpg",
    stock: 35,
    featured: false,
  },
]

export const mockServices = [
  {
    id: "grooming-basic",
    name: "Basic Grooming Package",
    description: "Essential grooming services including bath, brush, and nail trim",
    price: 45,
    duration: "1-2 hours",
    image: "/pet-grooming-service.png",
    features: ["Warm bath with premium shampoo", "Thorough brushing", "Nail trimming", "Ear cleaning"],
  },
  {
    id: "grooming-premium",
    name: "Premium Grooming Package",
    description: "Complete grooming experience with styling and special treatments",
    price: 85,
    duration: "2-3 hours",
    image: "/premium-pet-grooming.jpg",
    features: [
      "Everything in Basic Package",
      "Professional styling/haircut",
      "Teeth brushing",
      "Aromatherapy treatment",
      "Nail polish (optional)",
    ],
  },
  {
    id: "boarding-daily",
    name: "Daily Pet Boarding",
    description: "Safe and comfortable day care for your pets while you're away",
    price: 35,
    duration: "8-10 hours",
    image: "/pet-boarding-facility.png",
    features: ["Supervised playtime", "Feeding service", "Comfortable rest areas", "Regular health checks"],
  },
  {
    id: "boarding-overnight",
    name: "Overnight Pet Boarding",
    description: "Extended care with overnight accommodation in our facility",
    price: 65,
    duration: "24 hours",
    image: "/pet-overnight-boarding.jpg",
    features: [
      "Private sleeping quarters",
      "Multiple meals and snacks",
      "Exercise and playtime",
      "24/7 supervision",
      "Emergency vet access",
    ],
  },
  {
    id: "training-basic",
    name: "Basic Obedience Training",
    description: "Foundation training for puppies and young dogs",
    price: 120,
    duration: "4 weeks (1 hour/week)",
    image: "/dog-training-class.jpg",
    features: ["Sit, stay, come commands", "Leash training", "House training tips", "Socialization guidance"],
  },
  {
    id: "training-advanced",
    name: "Advanced Training Program",
    description: "Comprehensive training for behavioral issues and advanced commands",
    price: 250,
    duration: "8 weeks (1 hour/week)",
    image: "/advanced-dog-training.png",
    features: [
      "All basic commands",
      "Behavioral modification",
      "Advanced tricks",
      "Aggression management",
      "One-on-one sessions",
    ],
  },
]
